# @package _global_
model:
  charset_train: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ áéíóúÝÁÉÍÓÚÝČčĎďĚěŇňŘřŠšŤťŮůŽž"
  charset_test: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ áéíóúÝÁÉÍÓÚÝČčĎďĚěŇňŘřŠšŤťŮůŽž"